language: node_js
node_js:
    - "12.0"
install:
    - yarn
    - yarn secrets
script:
    - yarn build
    - yarn lint
    - yarn test
after_success:
    - yarn deploy
cache:
    directories:
        - node_modules
env:
    global:
        - secure: RxHdf/TSVtheawkfDwxuwC95AE99gpVU/5eAKVYndkE9nZSILzOgJ1Wc6PqeOY5y3B8Wo4c8I9HHwoX226hMzKUV2YTVn5Y16/4lkhFmqqLG0tOmUzaYsmLvSEQ58iurrDBujIxhsM7CwPkULNd4klWpx5lxLY7Zd9h0QzTdFM+OTo+H2BiYhZiC6vy/EZhsMOlevfazRJjjnnwYR/z2jr2Po5COHvEAsM2ZLNPzCip22/pOS5s81NCq0y3MP0oBGzMyRsKUZmy8Iw5ly4x4jPp9JrNY6SEnhnX27Bsv1k+l3MLjxr/FupCAd48kNBjm91vkxqjWdPjHu9OmSn8f6SB7exBflriMNWnE37eQDr/RKiXZuz6N45KRbzYyB3uj56PX670+MvA9yhsc204cLAyRu5SHsP3V3ik9i1q28By7G3lapHGRSDf3T2UXZH78rovgGDxsPsGjL+GPzHvjjEgzzMHBbRQpPHCJqVM/5JirorUCeqjIl8xmMCwFbZjGumIM0XG+3v8OyqVX1CdNWoL/lxILlAxiBtAeSb1C+KGuScM3rSfw1X/31ntpZnd6zIZj9mUosOo+489n0bq4g8qrIPRQd53NF40SysNPk6Q5QCo34ghSjYmdHPHf0qtrtIx9uYkuFHNFCN18CONlRXQMAWZkHW9AUNtVfD9fOZ8=
        - secure: EztGqiOF+Y3C7EJywCu4ICaejjZgQYwZ+Kkn+cSSVsxyCbXhsIx5nW2Hmdvr2B0Lnlg53AYYwA4h0c8r3KHWLB2nBYT2ZuRAmA6bHwk1//41obAv7u+C3BsJfgl6eQFeo0c6aKLVCss8DzWtNix/11xgmZEQ2gyVSmupOcMIuraUYsfAt99NFfgW0lVI0cfmJWRSAGJul+zcKYXPad9p+KO/IqMQ4jV80Rdk8Dza0GWg06ICbRlqqnSj/FndDscwrfD+JQIOiv2fmDOFk+Xll7pgME0vsK8nYD7sewsFMvzQvaKXiGFvhPeDDqRt6s5eNOy7I7ndAYBbIed5M1spbi5UvESs5CRe8PJMQcLr1WRezj+CoRXd6Swk6uc4YPbPXFgnub6VdwfJ8zKaXdmISwpbevdKB+eAw9E8jzbvbKRhrnBcB1jXDqT0rnNaJM+ffeN0YRvxZXBiHAM4jSR58qPx4vUJ4bfTqOxTmvn7X82RdmsQKeXPDGsrUAWvJOR6bYjuwGYP8nwHAHnVARF9+/97XbX1lyG6iEJfibmsWw/55SPByqF6oAO3RxouW6y+THfB910KEZMdmIKMMA51rdLOxYEx+ovDCMu4o+WikzfW6RmskHnxsc8fm7qx0b0i5Xgn7dadIDdAF1F+Y7qoMymApnnIL8mctV6IEIiyv4s=
