language: node_js
node_js:
cache: npm
script:
- yarn
- yarn secrets
- yarn build
- yarn lint
- yarn test
- deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: R2qsn5OUZN4nSAYN8PyeuB/oIzGFRO42wXNnUuRqayhoq3f122wg/Lx4aub9RLOcpxfeGiqQUZ/4If57fqL69WBeB/3+SROHDSA6TPPyUU2kX5nWqg2qavxs+JDs3g72L/qQY1Q2JS0s/+8TV2sbUXm5UCmxV36996qdjqeCGNXjNzGGmYAb9c2Y4p1zVBWdXRFQu/+xpQQkvtd3aO4wNHqShFHrkkDxDCjSxBmmc7fb59WyJp5osa9rIQJRLVW9EuXKDX/6vHZC95I+xu+D0h0di0Iy1AC5oySTDBqRNidHhM5aX7fXdyJ7wyLzI5+neuo+Q7w3f2u1TSdfNT1ejp0qq802nveeBBlbFqsknWM22TQacMPUuaF9WSuvaDMda5b43rVI+eeUAn80lFAWI5j+EAebmKM+QIbNRQzTdB61RJ6oDg6/4HHlKhhkHp59gCn8tvYBub5SupuVgtTn4+J0JpQmsDddMQHsQE3He47Aylz3R1h6QL/GalNL06MXAtbYD+mv2IBj2h+KClqAw9oC2LoGlNnkvEBAds6Ce+tLNKYgXyiEqeh+2Am+bVDMfLcxecfHAM1eW9Aazv8rQvRRIEVFIjn27HxKwqAKgApeQm9fyCjcYejh/DwA0xWx7cXLjPUzQAi8HXHpOhwG0OwN15yF6Q/jb8HJGEvB2kw=
  - secure: kjpatFKZseLWrM+mPDg8Ft1kzyqjkmddgVNBQIX/5gn9paXNj6LekVXyIo2zt0261mn9Qiy92wby/8F5lZ8tiNEsaCJa9R2ytiWR230h51zl84QZIE2cz55Jn6wcXsciolQ5kSqhJsG4BuCuorQfgsxS05xgdSi1agHN8bgcJLI/qljBg7kCpwAlhSVgnyF8LRvGyy496hNzzVEWP8FBPVsse7+YMEl3SUQoNSiGDq5Usakp2Navwn8RO8R4HxquxE35899FSr3Objyw7tOp8BHRsAutRcpQxcoiIdl7NxWuDX2ONtj1kW8ymetT/tMak/qPAfxIW+ssX9D0JhltDa/IYtG1JJ1QAK7pRLmoBy/rSpG21fMOJGlVB77F/kdGNRn0yrDffz5I9Xz9vOyefqFAm4r+sZ87GfOp3Es8t/lRsGHp3hvSUHHfZKjjmUvwf7qYwRas50b1XNIIbWslmBgR/drf8cAvDP465FBoR/FrhDfjseXEcqU/HhIl2BlpQIFlEuHJkfjbCz3JseUPyiUSoe07QB+KUZBA7Lu3drfPED/v/BkLoMrcQe33UPoNHgdPPA4fg8LOGSTkUgpqyexPAOukt319/bPRJ1AKbSkQu6K+0b51f40NQhoyQumRdtXWuiJuFCdflrGBiny0C3NPPTPtaQ0xxXRy+8XYN5U=
  - secure: Yt/1xUb9boQgqea95lV0lQ4il5kOSq051RhMiKJEjyTTZZxuBcfCeWvGh1DZyskVZKEIM3nGG2jgvNsO6cQI7MbGsxlR3shu8dWj72x2OI9EZHDoOkCxVQRIIlNW6FcfaoDGzmGi6fkImoTRnvcwptPW40HGO9bBHS6ukE4gWcrb3qv+iBsUfoQFEsPpXJ1cEZsbGFIMwqvja+IU7tF/PFZp2e5PjQ6mlw2FvP4eZEZTd/XQ++sHqSPEG9NrOpiG/SwwnL5tyv1co2z4wyA/5uBZ3iZHmMI90ptnk/d45saZGOB/AnY+4/SFgfW6Wvep2onljMvGVlLChFkJncTshh++tGAj+KeS4NU0FL144bP0t63qYFzm5zJJ0MNN4OnbI3siGdmuQWv49Ww7a3TN1a42KRl7/2Icl8nwfCFKytNP3hNeFimvO1pRAWsDZfOrtzBaKFhXSybWMatUKS5u2ct+wgbTsPyoa6fNG4JGghrK7O8e+JXUo/wV/Lmubk7AZRjwST5BfQ3VvA47jAx2ZxdROKgIbw0/GukhRnG6x6W8yVhSifb2KOn1lCaNx/YevmfdH57YJxhyq+ju5cnJzf95/8hEvdyXjli2HLz1xnG1o/oQu1rQWx4DE2P22tG42LP6Ryhzsge5Kt9fhbySDCJko5SC8bgVa0Rpw1rzwYE=
