language: node_js
node_js:
install:
    - yarn
script:
    - yarn secrets
    - yarn build
    - yarn lint
    - yarn test
after_success:
    - yarn deploy
cache:
    directories:
        - node_modules
