name: build
on:
    workflow_dispatch:
    push:
jobs:
    build:
        name: Build and upload to riffraff
        runs-on: ubuntu-latest
        # Allow GitHub to request an OIDC JWT ID token, to use with aws-actions/configure-aws-credentials
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - name: Install dependencies, build & run tests
              run: |
                yarn install --frozen-lockfile
                yarn build
                yarn test

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
                  aws-region: eu-west-1

            - name: Upload to riff-raff
              uses: guardian/actions-riff-raff@v2
              with:
                  configPath: conf/riff-raff.yaml
                  projectName: cms-fronts::front-press-monitor
                  buildNumberOffset: 17 # This is the last build number from TeamCity
                  contentDirectories: |
                      front-press-monitor:
                      - dist/front-press-monitor.zip
